# Generated by Django 5.1 on 2024-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigTableV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.TextField(blank=True, db_column='Gene_ID', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('sequence_name', models.TextField(blank=True, db_column='Sequence_Name', null=True)),
                ('gene_name', models.TextField(blank=True, db_column='Gene_Name', null=True)),
                ('other_name', models.TextField(blank=True, db_column='Other_Name', null=True)),
                ('transcript_name', models.TextField(blank=True, db_column='Transcript_Name', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
            ],
        ),
    ]
