# Generated by Django 5.1 on 2024-09-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_bigtablev2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
