# Generated by Django 5.1 on 2024-09-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_bigtablev3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BigTableV3',
        ),
    ]
