# Generated by Django 5.1 on 2024-09-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_bigtablev3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='gene_id',
            new_name='Gene_ID',
        ),
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='gene_name',
            new_name='Gene_Name',
        ),
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='other_name',
            new_name='Other_Name',
        ),
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='sequence_name',
            new_name='Sequence_Name',
        ),
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='transcript_name',
            new_name='Transcript_Name',
        ),
        migrations.RenameField(
            model_name='bigtablev2',
            old_name='type',
            new_name='Type',
        ),
    ]
